language: python
dist: jammy
python:
  - "3.8"
  - "3.9"
  - "3.10"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# command to run tests
script:
  - pytest tests/
