name: p_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=>3.8
  - numpy
  - scipy
  - pillow
  - matplotlib
  - astropy
  - pytest
  - sphinx
  - jupyter
  - ipykernel
  - nbsphinx
  - numpydoc
  - sphinx_rtd_theme
  - setuptools
  - pip:
      - flatstar